include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
  language:
    strict-raw-types: true
    strict-casts: true
  errors:
    invalid_annotation_target: ignore  

linter:
  rules:
    prefer_single_quotes: true
    always_use_package_imports: true
    prefer_const_constructors: true
    avoid_print: true
    unawaited_futures: true
